/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlserver;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.bind.DatatypeConverter;
import static qlserver.ConnectDth.getSqlConnection;

/**
 *
 * @author longp
 */
public class DANGKY extends javax.swing.JFrame {

    /**
     * Creates new form frmDangKyUser
     */
    public DANGKY() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        
        setSize(610, 330);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDangKy = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Ký Tài Khoản");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USERNAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 90, 102, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PASSWORD");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 140, 102, 40);

        btnDangKy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDangKy.setText("ĐĂNG KÝ");
        btnDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangKyMouseExited(evt);
            }
        });
        btnDangKy.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDangKyMouseMoved(evt);
            }
        });
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangKy);
        btnDangKy.setBounds(240, 210, 100, 30);

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat);
        btnThoat.setBounds(420, 210, 94, 30);
        jPanel1.add(txtusername);
        txtusername.setBounds(320, 90, 201, 30);
        jPanel1.add(txtpassword);
        txtpassword.setBounds(320, 140, 201, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ĐĂNG KÝ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 30, 182, 56);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlserver/hinh.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 610, 300);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        Connection conn = getSqlConnection();
        if (txtusername.getText().equals("") || txtpassword.getPassword().equals("")) {
            JOptionPane.showMessageDialog(null, "VUI LÒNG ĐIỀN VÀO USERNAME VÀ PASSWORD!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            MessageDigest md;
            try {
                String username = txtusername.getText();
                String password = new String(txtpassword.getPassword());
                md = MessageDigest.getInstance("MD5");
                md.update(password.getBytes());
                byte[] digest = md.digest();
                String myHash = DatatypeConverter.printHexBinary(digest).toUpperCase();
                String str = "insert into taikhoan values('" + username + "','" + myHash + "')";
                PreparedStatement ptsm = conn.prepareStatement(str);
                int rs = ptsm.executeUpdate();
                if (rs != 0) {
                    JOptionPane.showMessageDialog(null, "ĐĂNG KÍ THÀNH CÔNG","Information",JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    DANGNHAP dn = new DANGNHAP();
                    dn.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "ĐĂNG KÝ THẤT BẠI","Information",JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(null, ex,"Error",JOptionPane.ERROR_MESSAGE);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex,"Error",JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        JFrame Frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(Frame, "BẠN CÓ CHẮC CHẮN MUỐN THOÁT", "Exit",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            DANGNHAP dn = new DANGNHAP();
            dn.setVisible(true);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDangKyMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangKyMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangKyMouseMoved

    private void btnDangKyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangKyMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangKyMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DANGKY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DANGKY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DANGKY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DANGKY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DANGKY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
